version: '3'
services:

  app:
    build: ./app
    container_name: app
    ports:
      - "80:3000"
      # - "443:443"
    restart: always

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-evsoul:/webroots/evsoul.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-evsoul:
  certbot-letsencrypt:
